name: build and deploy

on: [push, pull_request]

env:
  IMAGE_NAME: focal-cmake

jobs:
  build-and-deploy:
    strategy:
      matrix:
        cmake-version: [3.20.2]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build focal-cmake:${{ matrix.cmake-version }}
      run: |
        docker build . -t ${IMAGE_NAME}:${{ matrix.cmake-version }} --build-arg CMAKE_VERSION=${{ matrix.cmake-version }}
    - name: docker login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: push focal-cmake:${{ matrix.cmake-version }}
      run: |
        docker tag ${IMAGE_NAME}:${{ matrix.cmake-version }} ${{ secrets.DOCKER_USERNAME }}/${IMAGE_NAME}:${{ matrix.cmake-version }}
        docker push ${{ secrets.DOCKER_USERNAME }}/${IMAGE_NAME}:${{ matrix.cmake-version }}
