name: build and deploy

on: [push, pull_request]

jobs:
  build:
    env:
      IMAGE_NAME: focal-cmake
    strategy:
      matrix:
        cmake-version: [3.20.2]
  runs-on: ubuntu-latest
  steps:
  - name: build focal-cmake:${{ matrix.cmake-version }}
  - uses: actions/checkout@v2
    run: |
      docker build . -t ${IMAGE_NAME}:${{ matrix.cmake-version }} --build-arg CMAKE_VERSION=${{ matrix.cmake-version }}
  - name: push focal-cmake:${{ matrix.cmake-version }}
    run: |
      docker tag ${IMAGE_NAME} ${{ secrets.DOCKER_USERNAME }}/${IMAGE_NAME}:${{ matrix.cmake-version }}
      docker push ${{ secrets.DOCKER_USERNAME }}/${IMAGE_NAME}:${{ matrix.cmake-version }}